m22/urls.py
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
  # """home url"""
  path('', views.HomeView.as_view(), name='home'),

  # """list urls"""
  path('machines/', views.MachineView.as_view(), name="machines"),
  path('active_machines/', views.ActiveMachinesView.as_view(), name="active_machines"),
  path('in_service_machines/', views.InServiceMachinesView.as_view(), name="in_service_machines"),

  path('providers/', views.ProviderView.as_view(), name='providers'),
  path('active_providers/', views.ActiveProviderView.as_view(), name='active_providers'),
  path('inactive_providers/', views.InactiveProviderView.as_view(), name='inactive_providers'),

  path("parts/", views.PartView.as_view(), name="parts"),
  path("maintenances/", views.MaintenanceView.as_view(), name="maintenances"),
  path("materials/", views.MaterialView.as_view(), name="materials"),
  path("labors/", views.LaborView.as_view(), name="labors"),

  # """detail urls"""
  path("<pk>/machines/", views.MachineDetailView.as_view(), name="machine_detail"),
  path("<pk>/providers/", views.ProviderDetailView.as_view(), name="provider_detail"),
  path("<pk>/parts/", views.PartDetailView.as_view(), name="part_detail"),
  path("<pk>/maintenances/", views.MaintenanceDetailView.as_view(), name="maintenance_detail"),
  path('<pk>/materials/', views.MaterialDetailView.as_view(), name="material_detail"),
  path('<pk>/labors/', views.LaborDetailView.as_view(), name="labor_detail"),

  # """create urls"""
  path('machines/new/', views.MachineCreateView.as_view(), name='new_machine'),
  path('providers/new/', views.ProviderCreateView.as_view(), name='new_provider'),
  path('parts/new/', views.PartCreateView.as_view(), name='new_part'),
  path('maintenances/new/', views.MaintenanceCreateView.as_view(), name='new_maintenance'),
  path('materials/new/', views.MaterialCreateView.as_view(), name="new_material"),
  path('labors/new/', views.LaborCreateView.as_view(), name="new_labor"),

  # """delete urls"""
  path("<pk>/machines/delete/", views.MachineDeleteView.as_view(), name="delete_machine"),
  path("<pk>/providers/delete/", views.ProviderDeleteView.as_view(), name="delete_provider"),
  path('<pk>/parts/delete/', views.PartDeleteView.as_view(), name="delete_part"),
  path("<pk>/maintenances/delete", views.MaintenanceDeleteView.as_view(), name="delete_maintenance"),
  path("<pk>/materials/delete", views.MaterialDeleteView.as_view(), name="delete_material"),
  path('<pk>/labor/delete', views.LaborDeleteView.as_view(), name="delete_labor"),

  # """create urls"""
  path("<pk>/machines/edit/", views.MachineUpdateView.as_view(), name="edit_machine"),

              ]

urlpatterns += staticfiles_urlpatterns()

maintenance22/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("m22.urls")),
]

m22/models.py
from django.db import models
from django.contrib.auth.models import User


class MachineCategory(models.Model):
    category = models.CharField(max_length=30)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return "/machines"

    def __str__(self):
        return f"""
        {self.category}
        """


class MachineStatus(models.Model):
    status = models.CharField(max_length=30)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return "/machines"

    def __str__(self):
        return f"""
        {self.status}
        """


class Machine(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    serial_number = models.CharField(max_length=14)
    manufactured = models.DateField()
    commissioned = models.DateField()
    price = models.FloatField(default=0)
    machine_category = models.ForeignKey(MachineCategory, on_delete=models.CASCADE)
    machine_status = models.ForeignKey(MachineStatus, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/machines"

    def __str__(self):
        return f"""
        name: {self.name}
        description: {self.description}
        price: {self.price}
        status: {self.machine_status}
        """


class ProviderType(models.Model):
    type = models.CharField(max_length=10)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return "/providers"

    def __str__(self):
        return f"""
        {self.type}
        """


class ProviderStatus(models.Model):
    status = models.CharField(max_length=50)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return "/providers"

    def __str__(self):
        return f"""
        {self.status}
        """


class Provider(models.Model):
    name = models.CharField(max_length=200)
    provider_type = models.ForeignKey(ProviderType, on_delete=models.CASCADE)
    provider_status = models.ForeignKey(ProviderStatus, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/providers"

    def __str__(self):
        return f"""
        name: {self.name}
        status: {self.provider_status}
        """


class PartCategory(models.Model):
    category = models.CharField(max_length=50)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return "/parts"

    def __str__(self):
        return f"""
        {self.category}
        """


class Part(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    part_category = models.ForeignKey(PartCategory, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    stock = models.FloatField(default=0)
    mu = models.CharField(max_length=2)
    target_stock = models.FloatField(default=0)
    provider_status = models.ForeignKey(ProviderStatus, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    link = models.CharField(max_length=500, default="https://www.emag.ro/")

    @property
    def diff_stock(self):
        return self.target_stock - self.stock

    @property
    def val_diff_stock(self):
        return (self.target_stock - self.stock) * self.price



    def get_absolute_url(self):
        return "/parts"

    def __str__(self):
        return f"""
        name: {self.name};
        price: {self.price};
        category: {self.part_category};
        stock: {self.stock};
        unit: {self.mu};
        target_stock: {self.target_stock};
        status: {self.provider_status};
        """


class MaintenanceType(models.Model):
    type = models.CharField(max_length=50)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)

    def get_absolute_url(self):
        return "/maintenances"

    def __str__(self):
        return f"""
         {self.type}
        """


class MaintenanceStatus(models.Model):
    status = models.CharField(max_length=50)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/maintenances"

    def __str__(self):
        return f"""
         {self.status}
        """


#   def save(self, *args, **kwargs):
#       user = get_current_user()
#       self.user = user
#       super(MaintenanceStatus, self).save(*args, **kwargs)

class Maintenance(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    maintenance_date = models.DateField()
    maintenance_status = models.ForeignKey(MaintenanceStatus, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    maintenance_type = models.ForeignKey(MaintenanceType, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/maintenance"

    def __str__(self):
        return f"""
         {self.id}
         {self.machine.name}
         {self.maintenance_status}
         {self.maintenance_type}
        """


class Material(models.Model):
    maintenance = models.ForeignKey(Maintenance, on_delete=models.CASCADE)
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    qty = models.FloatField(default=0)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def material_price(self):
        return self.qty * self.part.price

    def get_absolute_url(self):
        return "/materials"

    def __str__(self):
        return f"""
        {self.maintenance.id}
        name: {self.part.name}
        qty: {self.qty};

        """


class Labor(models.Model):
    maintenance = models.ForeignKey(Maintenance, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    document = models.CharField(max_length=5)
    value = models.FloatField(default=0)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/labor"

    def __str__(self):
        return f"""
        document: {self.document}
        value: {self.value};

        """

m22/views.py
from django.shortcuts import render

from django.views.generic import TemplateView
from django.views.generic import ListView

from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView

from .models import Machine
from .models import Provider
from .models import Part
from .models import Maintenance
from .models import Material
from .models import Labor
from .models import MachineStatus
from .models import ProviderStatus

from .forms import MachineForm
from .forms import ProviderForm
from .forms import PartForm
from .forms import MaintenanceForm
from .forms import MaterialForm
from .forms import LaborForm

from django.views import generic


class HomeView(TemplateView):
    template_name = "m22/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["machines"] = Machine.objects.all()
        context["providers"] = Provider.objects.all()
        context["parts"] = Part.objects.all()
        context["maintenances"] = Maintenance.objects.all()
        context["materials"] = Material.objects.all()
        context["labors"] = Labor.objects.all()
        return context


class MachineView(TemplateView):
    template_name = "m22/machine.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["machines"] = Machine.objects.all()
        context['name'] = 'Machines List'
        return context


class ActiveMachinesView(TemplateView):
    template_name = "m22/active_machine.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_status = MachineStatus.objects.get(status="active")
        context["active_machines"] = Machine.objects.filter(machine_status=active_status)
        context['name'] = 'Active Machines List'
        return context


class InServiceMachinesView(TemplateView):
    template_name = "m22/in_service_machine.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        in_service_status = MachineStatus.objects.get(status='in service')
        context["in_service_machines"] = Machine.objects.filter(machine_status=in_service_status)
        context['name'] = 'In Service Machines List'
        return context


class ProviderView(TemplateView):
    template_name = "m22/provider.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["providers"] = Provider.objects.all()
        return context


class ActiveProviderView(TemplateView):
    template_name = "m22/active_provider.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_status = ProviderStatus.objects.get(status="active")
        context["active_providers"] = Provider.objects.filter(provider_status=active_status)
        return context


class InactiveProviderView(TemplateView):
    template_name = "m22/inactive_provider.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        inactive_status = ProviderStatus.objects.get(status="inactive")
        context["inactive_providers"] = Provider.objects.filter(provider_status=inactive_status)
        return context


class PartView(TemplateView):
    template_name = "m22/part.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["parts"] = Part.objects.all()
        return context


class MaintenanceView(TemplateView):
    template_name = "m22/maintenance.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["maintenances"] = Maintenance.objects.all()
        return context


class MaterialView(TemplateView):
    template_name = "m22/material.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['materials'] = Material.objects.all()
        return context


class LaborView(TemplateView):
    template_name = "m22/labor.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['labors'] = Labor.objects.all()
        return context


# Detail Views
class MachineDetailView(generic.DetailView):
    context_object_name = 'machine_detail'
    model = Machine
    template_name = "m22/machine_detail.html"


class ProviderDetailView(generic.DetailView):
    context_object_name = 'provider_detail'
    model = Provider
    template_name = "m22/provider_detail.html"


class PartDetailView(generic.DetailView):
    context_object_name = 'part_detail'
    model = Part
    template_name = "m22/part_detail.html"


class MaintenanceDetailView(generic.DetailView):
    context_object_name = 'maintenance_detail'
    model = Maintenance
    template_name = "m22/maintenance_detail.html"


class MaterialDetailView(generic.DetailView):
    context_object_name = 'material_detail'
    model = Material
    template_name = "m22/material_detail.html"


class LaborDetailView(generic.DetailView):
    context_object_name = 'labor_detail'
    model = Labor
    template_name = "m22/labor_detail.html"


# Form views

class MachineCreateView(CreateView):
    template_name = "m22/new_machine.html"

    model = Machine
    success_url = '/machines/'
    form_class = MachineForm


class ProviderCreateView(CreateView):
    template_name = "m22/new_provider.html"

    model = Provider
    success_url = '/providers/'
    form_class = ProviderForm


class PartCreateView(CreateView):
    template_name = "m22/new_part.html"

    model = Part
    success_url = '/parts/'
    form_class = PartForm


class MaintenanceCreateView(CreateView):
    template_name = "m22/new_maintenance.html"

    model = Maintenance
    success_url = '/maintenances/'
    form_class = MaintenanceForm


class MaterialCreateView(CreateView):
    template_name = "m22/new_material.html"

    model = Material
    success_url = '/materials/'
    form_class = MaterialForm


class LaborCreateView(CreateView):
    template_name = 'm22/new_labor.html'

    model = Labor
    success_url = '/labors/'
    form_class = LaborForm


# Delete views


class MachineDeleteView(DeleteView):
    template_name = 'm22/delete_machine.html'
    model = Machine
    success_url = '/machines/'


class ProviderDeleteView(DeleteView):
    template_name = 'm22/delete_provider.html'
    model = Provider
    success_url = '/providers/'


class PartDeleteView(DeleteView):
    template_name = 'm22/delete_part.html'
    model = Part
    success_url = '/parts/'


class MaintenanceDeleteView(DeleteView):
    template_name = 'm22/delete_maintenance.html'
    model = Maintenance
    success_url = '/maintenances/'


class MaterialDeleteView(DeleteView):
    template_name = 'm22/delete_material.html'
    model = Material
    success_url = '/materials/'


class LaborDeleteView(DeleteView):
    template_name = 'm22/delete_labor.html'
    model = Labor
    success_url = '/labors/'


# Update Views

class MachineUpdateView(UpdateView):
    template_name = "m22/new_machine.html"

    model = Machine
    success_url = '/machines/'
    form_class = MachineForm

m22/templates/m22/active_machine.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}





<!--active machines-->
<a href="{% url 'new_machine' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">Add a new machine</button> </a>
<br>
<br>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Machines Status
  </button>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'machines' %}">All</a>
    <a class="dropdown-item" href="{% url 'active_machines' %}">Active</a>
    <a class="dropdown-item" href="{% url 'in_service_machines' %}">In Service</a>
  </div>

</div>

<br>
<br>

<div class="container">
  <h2>Active Machines</h2>
  <p>Here we can find all the active machines instances with their basic info</p>
  <table class="table table-success table-hover">
    <thead>
       <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>PRICE</th>
           <th>STATUS</th>

     </tr>
    </thead>
      <tbody>
           {% for machine in active_machines %}
            <tr>
                <td>{{machine.id}}</td>
                <td><a class="text-dark" href="http://localhost:8000/{{machine.id}}/machines/">{{machine.name}}</a></td>
                <td>{{machine.price}}$</td>
                <td>{{machine.machine_status}}</td>
                <td><a href="{% url 'delete_machine' pk=machine.id %}" class="btn btn-danger"> Remove </a> </td>

            </tr>

        {% endfor %}

    </tbody>
  </table>
</div>

<br>
<br>
<a href="{% url 'new_machine' %}"><button type="button" class="btn btn-secondary btn-lg btn-block">Add a new machine</button> </a>
{% endblock %}

m22/templates/m22/active_provider.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}
<a href="http://localhost:8000/providers/new/"><button type="button" class="btn btn-secondary btn-lg btn-block">Add a new provider</button> </a>
<br>
<br>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Provider Status
  </button>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'providers' %}">All</a>
    <a class="dropdown-item" href="{% url 'active_providers' %}">Active</a>
    <a class="dropdown-item" href="{% url 'inactive_providers' %}">Inactive</a>
  </div>

</div>

<br>
<br>

<div class="container">
  <h2>Active Providers</h2>
  <p>Here we can find all the providers instances with their basic info</p>
  <table class="table table-success table-hover">
    <thead>
       <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>TYPE</th>
        <th>STATUS</th>
     </tr>
    </thead>
      <tbody>
           {% for provider in active_providers %}
            <tr>
                <td>{{provider.id}}</td>
                <td><a class="text-dark" href="http://localhost:8000/{{provider.id}}/providers/">{{provider.name}}</a></td>
                <td>{{provider.provider_type}}</td>
                <td>{{provider.provider_status}}</td>
                <td><a href="{% url 'delete_provider' pk=provider.id %}" class="btn btn-danger"> Remove </a> </td>
            </tr>

        {% endfor %}

    </tbody>
  </table>
</div>
<br>
<br>
<a href="http://localhost:8000/providers/new/"><button type="button" class="btn btn-secondary btn-lg btn-block">Add a new provider</button> </a>

{% endblock %}

m22/templates/m22/delete_maintenance.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <p>Are you sure you want to delete {{maintenance.maintenance_type}} for {{maintenance.machine.name}} - {{maintenance.machine.description}}</p>
    <button type="submit" class="btn btn-danger my-5">Confirm</button>
  </form>

{% endblock %}

m22/templates/m22/delete_material.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <p>Are you sure you want to delete {{material.maintenance.maintenance_type}} for {{material.maintenance.machine.name}} {{material.maintenance.machine.description}} </p>
    <button type="submit" class="btn btn-danger my-5">Confirm</button>
  </form>

{% endblock %}

m22/templates/m22/delete_provider.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form }}
    <p>Are you sure you want to delete provider - {{provider.name}} </p>
    <button type="submit" class="btn btn-danger my-5">Confirm</button>
  </form>

{% endblock %}

m22/templates/m22/machine_detail.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

<td><a href="{% url 'machines' %}" class="btn btn-dark"> Back to Machines </a> </td>
<br>
<br>



<div class="container">
    <div class="card p-3 mb-2" style="width: 28rem;">
        <div class="alert alert-primary p-4 border rounded" role="alert">
      <div class="card-header font-weight-bold text-center">
            <div class="text-dark">{{machine_detail.description}}</div>
      </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item p-3 mb-2 bg-dark text-white">name: {{machine_detail.name}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">serial_number: {{machine_detail.serial_number}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">manufactured: {{machine_detail.manufactured}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">commissioned: {{machine_detail.commissioned}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">price: {{machine_detail.price}} $</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">category: {{machine_detail.machine_category}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">status: {{machine_detail.machine_status}}</li>
        </ul>
    </div>
</div>
<br>



<div class="container">
<div class="alert alert-primary p-4 border rounded" role="alert">
  <div class="font-weight-bold text-center text-dark">Here are all the Maintenances needed for {{machine_detail.description}}, {{machine_detail.name}}</div>
<table class="table table-dark table-hover">
    <thead>
       <tr>
           <th>TYPE</th>
        <th>DATE</th>
        <th>STATUS</th>
        <th>CREATED</th>
        <th>RESPONSIBLE USER</th>
     </tr>
    </thead>
      <tbody>
           {% for maintenance in machine_detail.maintenance_set.all %}

            <tr>
                <td>{{maintenance.maintenance_type}}</td>
                <td>{{maintenance.maintenance_date}}</td>
                <td>{{maintenance.maintenance_status}}</td>
                <td>{{maintenance.created_on}}</td>
                <td>{{maintenance.user}}</td>
            </tr>
        {% endfor %}

    </tbody>
  </table>
</div>
</div>







<div class="container"></div>

<div class="alert alert-primary p-4 border rounded" role="alert">

<div class="table table-dark table-hover" role="alert">


{% for maintenance in machine_detail.maintenance_set.all %}

<div class="table table-dark p-3 border" role="alert">

    <div class=" font-weight-bold">
    {{maintenance.id}}.
    {{maintenance.maintenance_type}}
    </div>
    Here are all the parts that needs to be changed in this maintenance procedure

</div>

{% for material in maintenance.material_set.all %}

<div class="table table-dark table-hover p-2" role="alert">

    <div>
        <br>name: {{material.part.name}}
        <br>quantity: {{material.qty}} {{material.part.mu}}
        <br> description: {{material.part.description}}
    </div>

</div>


{% endfor %}
{% endfor %}

</div>
</div>
</div>
{% endblock %}

m22/templates/m22/new_material.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

  <form action="{% url 'new_material' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary my-5">Submit</button>
  </form>
{% endblock %}

m22/templates/m22/new_provider.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

  <form action="{% url 'new_provider' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary my-5">Submit</button>
  </form>
{% endblock %}

m22/templates/m22/provider_detail.html
{% extends 'base.html' %}
{% block title %}Maintenance M22 - Machines{% endblock %}
{% block content %}

<td><a href="{% url 'providers' %}" class="btn btn-dark"> Back to Providers </a> </td>
<br>
<br>

<div class="container">
    <div class="card p-3 mb-2" style="width: 28rem;">
        <div class="alert alert-primary p-4 border rounded" role="alert">
      <div class="card-header font-weight-bold text-center">
            <div class="text-dark">{{provider_detail.name}}</div>
      </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item p-3 mb-2 bg-dark text-white">type: {{provider_detail.provider_type}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">status: {{provider_detail.provider_status}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">partner since: {{provider_detail.created_on}}</li>
            <li class="list-group-item p-3 mb-2 bg-dark text-white">responsible user: {{provider_detail.user}}</li>
        </ul>
    </div>
</div>
</div>

<div class="container">
<div class="alert alert-primary p-4 border rounded" role="alert">
  <div class="font-weight-bold text-center text-dark">Here are all the Parts available to buy from {{provider_detail.name}}</div>
<table class="table table-dark table-hover">
    <thead>
       <tr>
        <th>NAME</th>
        <th>PRICE</th>
        <th>CATEGORY</th>
        <th>STOCK</th>
        <th>RESPONSIBLE USER</th>
     </tr>
    </thead>
      <tbody>
           {% for part in provider_detail.part_set.all %}
            <tr>
                <td>{{part.name}}</td>
                <td>{{part.price}}$</td>
                <td>{{part.part_category}}</td>
                <td>{{part.stock}}</td>
                <td>{{part.user}}</td>
            </tr>

        {% endfor %}

    </tbody>
  </table>
</div>
</div>
{% endblock %}



description = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    part_category = models.ForeignKey(PartCategory, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    stock = models.FloatField(default=0)
    mu = models.CharField(max_length=2)
    target_stock = models.FloatField(default=0)
    provider_status = models.ForeignKey(ProviderStatus, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    modified_on = models.DateField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)